### ISSUE TITLE
dimension of input

### ISSUE THREAD

**Issue by fnsrc** [ristea/septr#1]
Hi,

In septr.py, 
def forward(self, x):
        x, cls_token = self.transformer[0](x, self.cls_token)

        for i in range(0, len(self.transformer)):
            x, cls_token = self.transformer[i](x, cls_token)

        cls_token = cls_token[:, 0, 0, :]
        x = self.fc(cls_token)
        return x
What are four argument of input "x"? in x=(a, b, c, d), what are the dimensions of a, b, c and d?
Thanks in advance.

**Comment by ristea** [comment]
For x we have [batch size x num channels x frequency axis x time axis]. In our case we had [4 x 1 x 128 x 128]

**Comment by fnsrc** [comment]
Hi, 
Thanks for your response!
I test the following code, however, i get this error:

>>from septr import SeparableTr
>>A = SeparableTr(channels=1, input_size=(128, 128), num_classes=35, depth=1, heads=5, mlp_dim=256, dim_head=256,
                 down_sample_input=None, dim=256)

>>x = torch.randn(4, 1, 128, 128)
>>output = A(x)

------------------------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-7-d23e858cc3dc>](https://localhost:8080/#) in <module>()
----> 1 output = A(x)

5 frames

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py](https://localhost:8080/#) in forward(self, input)
    101 
    102     def forward(self, input: Tensor) -> Tensor:
--> 103         return F.linear(input, self.weight, self.bias)
    104 
    105     def extra_repr(self) -> str:

RuntimeError: mat1 and mat2 shapes cannot be multiplied (65536x256 and 1x256)
