### ISSUE TITLE
I think i found bug in SeparableTr

### ISSUE THREAD

**Issue by JaegeonJo** [ristea/septr#3]
First of all, thank you for your great works. 

When I try to train septr, I got following error.
```
[/torch/nn/modules/linear.py] in forward(self, input)
101
102 def forward(self, input: Tensor) -> Tensor:
--> 103 return F.linear(input, self.weight, self.bias)
104
105 def extra_repr(self) -> str:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (65536x256 and 1x256)
```

After little a bit of debugging, I concluded that following code is implementation mistake.
```python
# in septr.py
# line 34-37
def forward(self, x):
    x, cls_token = self.transformer[0](x, self.cls_token)

    for i in range(0, len(self.transformer)):
        x, cls_token = self.transformer[i](x, cls_token)
```

According to code, 0th transformer block is forwarded twice.  ( Error occurs )
I think range should be `(1, len(self.tansformer))`.

Thanks!

**Comment by ristea** [comment]
Thank you! Problem solved.
