### ISSUE TITLE
Not even a requirements file

### ISSUE THREAD

**Issue by MatteoSid** [ristea/septr#6]
You didn't even put a requirements.txt file, but how dare you post this code in Papers with Code?

**Comment by raduionescu** [comment]
Dear Matteo Donato,

Thank you for reaching out! The code should be compatible with python 3.6.8 or later, pytorch 1.4 or later, einops 0.5 or later. If you encounter any troubles in your environment, you are welcome to report the specific issue.

Nevertheless, please note that we did not post our code to "Papers with Code". The code might have been added via automatic indexing or by someone else. Still, if you are not happy with the code, you have the option to simply ignore it.
